<?php

/**
 * @file
 * islandora_lab_object_specimen.install
 */

function islandora_lab_object_specimen_install() {
  module_load_include('inc', 'islandora', 'includes/solution_packs');
  islandora_install_solution_pack('islandora_lab_object_specimen');

}

function islandora_lab_object_specimen_schema(){
  echo "come on now";
  exit(0);
  $schema["sponge_class"] = array(
    'description' => "Holds autocomplete data for sponge classes",
    'fields' => array(
      'class' => array(
        'description' => "The taxonomic class for porifera's",
        'type' => 'varchar',
        'length' => 50,
        'not null' => TRUE,
        ),
      ),
      'unique keys' => array(
        'class' => array('class'),
      ),
      'primary key' => array('class'),
  );
  return $schema;
}





