<?php

/** namespace is 'bioinformatics:exampleCM' instead of 'islandora:exampleCM' */


/**
 * * Implements hook_islandora_required_objects()
 * */
function islandora_bioinformatics_specimen_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'islandora_bioinformatics_specimen');
  $content_model = $connection->repository->constructObject('islandora:specimenCM');
  $content_model->owner = 'fedoraAdmin';
  $content_model->label = 'Bioinformatics Specimen Content Model';
  $content_model->models = 'fedora-system:ContentModel-3.0';
  // DS-COMPOSITE-MODEL Datastream.
  $datastream = $content_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/specimen_ds_composite_model.xml", FALSE);
  $content_model->ingestDatastream($datastream);
  return array(
    'islandora_bioinformatics_specimen' => array(
      'title' => 'Bioinformatics Specimen',
      'objects' => array(
          $content_model,
      ),
    ),
  );
}

function islandora_bioinformatics_specimen_islandora_xml_form_builder_forms() {
  $module_path = drupal_get_path('module', 'islandora_bioinformatics_specimen');
  return array(
    'Specimen Form' => array(
      'form_file' => "$module_path/xml/specimen_form.xml",
    ),
  );
}

function islandora_bioinformatics_specimen_islandora_xml_form_builder_form_associations() {
  $module_path = drupal_get_path('module', 'islandora_bioinformatics_specimen');
  return array(
    'islandora_bioinformatics_specimen_form' => array(
      'content_model' => 'islandora:specimenCM',
      'form_name' => 'Specimen Form',
      'dsid' => 'EML',
      'title_field' => array(
        'dataset',
      ),
      'transform' => '',
      'template' => FALSE,
    ),
  );
}

function islandora_bioinformatics_specimen_islandora_specimenCM_islandora_ingest_steps(array $configuration){
  return array(
    'islandora_bioinformatics_specimen_file_upload' => array(
      'weight' => 10,
      'type' => 'form',
      'form_id' => 'islandora_bioinformatics_specimen_upload_form',
      'module' => 'islandora_bioinformatics_specimen',
      'file' => 'includes/islandora_bioinformatics_specimen_upload.form.inc'
    )
  );
}

/**
 * Implements hook_preprocess_theme().
 * This is a Drupal hook, not supplied by islandora.
 * Variables required for display are assembled here and passed to the template file
 * defined in the theme function.  The function defines islandora_porcus, which
 * expands to islandora-porcus.tpl.php.
 * The isandora object has been added to the $variables array by 
 * hook_CMODEL_PID_islandora_view_object(), whihc in this case is
 * islandora_porcus_islandora_porcusCModel_islandora_view_object
 * 
 */
function islandora_bioinformatics_specimen_preprocess_islandora_bioinformatics_specimen(array &$variables) {

  $islandora_object = $variables['islandora_object'];
  // Thumbnail.
  if (isset($islandora_object['IMG'])) {
    $thumbnail_size_url = url("islandora/object/{$islandora_object->id}/datastream/IMG/view");
    $params = array(
      'title' => $islandora_object->label,
      'path' => $thumbnail_size_url,
    );
    $variables['islandora_thumbnail_img'] = theme('image', $params);
  }
}


/**
 * Implements hook_theme().
 *
 * We supply a pattern so we can overide templates at the theme level if needed.
 * we can append a pid to a template and the new template file will be called
 * (the pids colon should be replaced with a dash)
 */
function islandora_bioinformatics_specimen_theme($existing, $type, $theme, $path) {
  return array(
    'islandora_bioinformatics_specimen' => array(
      'template' => 'theme/specimen_theme',
      'pattern' => 'islandora_bioinformatics_specimen__',
      'variables' => array('islandora_object' => NULL),
    ),
  );
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 * If an object's behavior is defined by the islandora_bioinformatics_specimen content model
 * this hook takes the object being displayed and sends it to the theme function described by islandora_porcus_theme.
 * A reference to the islandora object being displayed is added here as a member of
 * the array whihc makes the seond argument to the theme function.
 */
function islandora_bioinformatics_specimen_islandora_specimenCM_islandora_view_object($object, $page_number, $page_size) {
  $output = theme('islandora_bioinformatics_specimen', array('islandora_object' => $object));
  return array('' => $output);
}
